FROM osixia/openldap:latest
ENV apt="git"
ENV git_url="https://github.com/matiasgonzalocalvo"
ENV challenge="ChallengeMercadoLibre2"
RUN apt update ; apt install -y ${apt}
RUN git clone ${git_url}/${challenge}
WORKDIR ${challenge}
COPY ldap/u_org.ldif /container/service/slapd/assets/config/bootstrap/ldif/
